# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
# Edit this file to change the sponsor button shown on the repo home page.

github: poli0981
ko_fi: skullmute
buy_me_a_coffee: skullmute
patreon: skullmute
custom:
  - https://paypal.me/DungDang212
